dog_finder/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from posts.views import index

urlpatterns = [
                  path('admin/', admin.site.urls),
                  url(r'^', include(('posts.urls', 'posts'), namespace="posts")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.urls import path
from posts.views import index, hi, dog_registration

urlpatterns = [
    path('', index, name=''),
    path('dog-registration', dog_registration, name='dog-registration'),
    path('hi', hi, name='hi'),

]

posts/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


def name_path_file(path, filename):
    import uuid
    uuid_for_filename = uuid.uuid4().hex[:6]
    filename = "{uuid}-{filename}".format(
        uuid=uuid_for_filename,
        filename=filename,
    )
    return '/'.join([path, filename])


def upload_to_image(instance, filename):
    return name_path_file('images/pets', filename)


def upload_to_image_qr(instance, filename):
    return name_path_file('images/qr', filename)


class Profile(User):
    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

    address = models.CharField(max_length=255)
    contact_no = models.CharField(max_length=168)

    def __str__(self):
        return f'{self.get_full_name()}'


class TypeofPet(BaseModel):
    class Meta:
        ordering = ('name',)

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=62)
    description = models.CharField(max_length=62, null=True, blank=True)

    def __str__(self):
        return f'{self.name}-{self.description}'


class Pet(BaseModel):
    GENDER = (
        ('MALE', 'MALE'),
        ('FEMALE', 'FEMALE'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=62, null=True, blank=True)
    height = models.CharField(max_length=62, null=True, blank=True)
    age = models.IntegerField()
    gender = models.CharField(choices=GENDER, max_length=64)
    image = models.ImageField(upload_to=upload_to_image)
    is_done = models.BooleanField(default=False)
    is_found = models.BooleanField(default=False)
    type_of_pet = models.ForeignKey(to=TypeofPet, on_delete=models.SET_NULL, blank=False, null=True)
    qr_no = models.CharField(max_length=255, null=True, blank=True)
    qr_image = models.ImageField(upload_to=upload_to_image_qr)

    def __str__(self):
        return f'{self.name}-{self.age}'


class PostLost(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    profile_id = models.ForeignKey(to=Profile, on_delete=models.SET_NULL, null=True, blank=True)
    pet = models.ForeignKey(to=Pet, on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField(max_length=255)

    def __str__(self):
        return f'{self.pet.name}'


class PostFound(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    profile_id = models.ForeignKey(to=Profile, on_delete=models.SET_NULL, null=True, blank=True)
    pet = models.ForeignKey(to=Pet, on_delete=models.SET_NULL, null=True, blank=True)
    found_by = models.CharField(max_length=255, verbose_name="Full Name")
    contact_no = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = models.TextField(max_length=255)

    def __str__(self):
        return f'{self.pet.name}'


class Message(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    profile_id = models.ForeignKey(to=Profile, on_delete=models.SET_NULL, null=True, blank=True)
    post_lost = models.ForeignKey(to=PostLost, on_delete=models.SET_NULL, null=True, blank=True)
    post_found = models.ForeignKey(to=PostFound, on_delete=models.SET_NULL, null=True, blank=True)
    comment = models.TextField(max_length=255)

    def __str__(self):
        return f'{self.comment}'

posts/views.py
from django.http import HttpResponse
from django.shortcuts import render
from posts.models import Pet, TypeofPet


def hi(request):
    return HttpResponse("Hello is me!!")


def dog_registration(request):
    title = "Register Dog"
    # content_header = "Pending Request"
    type_of_pet = TypeofPet.objects.all()
    template = "base/dog_registration.html"

    content = {
        'title': title,
        'breed_type': type_of_pet
    }
    return render(request, template, content)


def index(request):
    title = "Login"
    # contentheader = "Pending Request"
    # data = Requests.objects.filter(trash=0, status=0).order_by('date_created')
    template = "base/login.html"

    content = {
        'title': title,
        # 'data': data
    }
    return render(request, template, content)



def registration(request):
    title = "Create"
    # contentheader = "Pending Request"
    # data = Requests.objects.filter(trash=0, status=0).order_by('date_created')
    template = "requests/all-pending-request.html"

    content = {
        'title': title,
        # 'data': data
    }
    return render(request, template, content)


def login(request):
    title = "Create"
    # contentheader = "Pending Request"
    # data = Requests.objects.filter(trash=0, status=0).order_by('date_created')
    template = "requests/all-pending-request.html"

    content = {
        'title': title,
        # 'data': data
    }
    return render(request, template, content)

templates/base/dog_registration.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dog Finder</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<header class="header_registration">
    <nav class="navbar navbar-style">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#micon">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href=""> <img class="logo" src="../../static/images/logo.png"></a>
            </div>
            <div class="collapse navbar-collapse" id="micon">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="homepage.html">Home</a></li>
                    <li><a href="">Feed</a></li>
                    <li><a href="">Creat Post</a></li>
                    <li><a href="">About</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="wrapper">
        <div class="dog_title">
            Dog Registration
        </div>
        <div class="form">
            <div class="inputfield">
                <label>Dog's Name</label>
                <input type="text" class="input">
            </div>
            <div class="inputfield">
                <label>Age</label>
                <input type="text" class="input">
            </div>
            <div class="inputfield">
                <label>Height</label>
                <input type="text" class="input">
            </div>
            <div class="inputfield">
                <label>Breed</label>
                <div class="custom_select">

                    <select>
                        {% for item in breed_type %}
                            <option value="{{ item.id }}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>


            <div class="inputfield">
                <label>Gender</label>
                <div class="custom_select">
                    <select>
                        <option value="">Select</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>
                </div>
            </div>

            <form action="#">
                <div class="inputfield">
                    <label>Upload Images</label>
                    <input type="file" id="myFile" name="filename" class="up_input">

                </div>
            </form>


            <div class="inputfield">
                <input type="submit" value="Register" class="btn">
            </div>
        </div>
    </div>
</header>
</body>
</html>

templates/base/forgot_password.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dog Finder</title>
    <link rel="stylesheet" type="text/css" href="../../static/css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<header class="header_forgotpass">
    <nav class="navbar navbar-style">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#micon">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href=""> <img class="logo" src="../../static/images/logo.png"></a>
            </div>
            <div class="collapse navbar-collapse" id="micon">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="homepage.html">Home</a></li>
                    <li><a href="">Feed</a></li>
                    <li><a href="">Creat Post</a></li>
                    <li><a href="">About</a></li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="form-container">
        <form action="#" method="POST" class="form-wrap">
            <h2>Forgot Password</h2>
            <div class="form-box">
                <input type="text" placeholder="Email Address"/>
            </div>
            <div class="form-submit">
                <input type="submit" value="Send Code"/>
            </div>
        </form>
    </div>


</header>
</body>
</html>

templates/base/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dog Finder</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body class="login">

<header class="header_login">
    <nav class="navbar navbar-style">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#micon">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href=""> <img class="logo" src="../../static/images/logo.png"></a>
            </div>
            <div class="collapse navbar-collapse" id="micon">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="homepage.html">Home</a></li>
                    <li><a href="">Feed</a></li>
                    <li><a href="{% url 'posts:dog-registration' %}">Creat Post</a></li>
                    <li><a href="">About</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-4">
                <div class="wrapper">
                    <div class="title-text">
                        <div class="title login">
                            Login Account
                        </div>
                        <div class="title signup">
                            Sign Up
                        </div>
                    </div>
                    <div class="form-container">
                        <div class="slide-controls">
                            <input type="radio" name="slide" id="login" checked>
                            <input type="radio" name="slide" id="signup">
                            <label for="login" class="slide login">Login</label>
                            <label for="signup" class="slide signup">Signup</label>
                            <div class="slider-tab"></div>
                        </div>
                        <div class="form-inner">
                            <form action="#" class="login">
                                <div class="field">
                                    <input type="text" placeholder="Email Address" required>
                                </div>
                                <div class="field">
                                    <input type="password" placeholder="Password" required>
                                </div>
                                <div class="pass-link">
                                    <a href="forgot_password.html">Forgot password?</a>
                                </div>
                                <div class="field btn">
                                    <div class="btn-layer"></div>
                                    <input type="submit" value="Login">
                                </div>
                                <div class="signup-link">
                                    Don't have an account? <a href="">Sign up here</a>
                                </div>
                            </form>
                            <form action="#" class="signup">
                                <div class="field">
                                    <input type="text" placeholder="First name" required>
                                </div>
                                <div class="field">
                                    <input type="text" placeholder="Last name" required>
                                </div>
                                <div class="field">
                                    <input type="text" placeholder="Email Address" required>
                                </div>
                                <div class="field">
                                    <input type="password" placeholder="Password" required>
                                </div>

                                <div class="field btn">
                                    <div class="btn-layer"></div>
                                    <input type="submit" value="Signup">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <script>
                    const loginText = document.querySelector(".title-text .login");
                    const loginForm = document.querySelector("form.login");
                    const loginBtn = document.querySelector("label.login");
                    const signupBtn = document.querySelector("label.signup");
                    const signupLink = document.querySelector("form .signup-link a");
                    signupBtn.onclick = (() => {
                        loginForm.style.marginLeft = "-50%";
                        loginText.style.marginLeft = "-50%";
                    });
                    loginBtn.onclick = (() => {
                        loginForm.style.marginLeft = "0%";
                        loginText.style.marginLeft = "0%";
                    });
                    signupLink.onclick = (() => {
                        signupBtn.click();
                        return false;
                    });
                </script>
                <div>
                    <div>
                        <div>
</header>
</body>
</html>